### ISSUE TITLE
Semihosting cannot be enabled on GNU/Eclipse

### ISSUE THREAD

**Issue by 0xd35a2ee** [OpenNuvoton/M2351BSP#1]
Hello there,

I am using the provided [GNU/Eclipse development toolchain](https://m2351.nuvoton.com/resource/) and a [NuMaker PFM-M2351 development board](https://direct.nuvoton.com/en/numaker-pfm-m2351). I would like to turn on semihosting so that `printf` statements can be read from the OpenOCD console. Unfortunately, enabling semihosting is not possible at the moment. My approach/analysis is explained as follows.

## Steps to reproduce:
1. Create a new Secure and Non-secure project in GNU Eclipse, having updated all vendor packs.
2. Try to execute the steps described below.

## Detailed analysis

1. Firstly, I tried to enable the ARM semihosting directly through the Eclipse GUI via **Debug > Debug Configurations > Run Tab > Enable ARM semihosting**. As a result nothing changed. No printouts were shown on the OpenOCD console.
2. As a result of (1) I inspected the `Library/retarget.c` file as it contains the semihosting drivers. Apparently it needs to be compiled using the `DEBUG_ENABLE_SEMIHOST` preprocessor as described [here](http://www.nuvoton.com/resource-files/NuLink_Adapter_User_Manual_EN_V1.01.pdf) and [here](https://github.com/OpenNuvoton/M2351BSP/blob/a9918882bf799788250c8fb3916a90e114ac9583/SampleCode/Semihost/main.c#L43). When compiling with the `DEBUG_ENABLE_SEMIHOST` preprocessor enabled, the following error occurs:
```
Building file: ../Library/retarget.c
Invoking: Cross ARM GNU C Compiler
arm-none-eabi-gcc -mcpu=cortex-m23 -march=armv8-m.base -mthumb -mlittle-endian -Og -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections  -g -DDEBUG_PORT=UART1_NS -DDEBUG_ENABLE_SEMIHOST -I"../Library/CMSIS/Include" -I"../Library/Device/Nuvoton/M2351/Include" -I"../Library/StdDriver/inc" -std=gnu11 -MMD -MP -MF"Library/retarget.d" -MT"Library/retarget.o" -c -o "Library/retarget.o" "../Library/retarget.c"
../Library/retarget.c: In function 'SendChar':
../Library/retarget.c:336:5: error: 'g_buf' undeclared (first use in this function)
     g_buf[g_buf_len++] = ch;
     ^~~~~
../Library/retarget.c:336:5: note: each undeclared identifier is reported only once for each function it appears in
../Library/retarget.c:336:11: error: 'g_buf_len' undeclared (first use in this function)
     g_buf[g_buf_len++] = ch;
           ^~~~~~~~~
../Library/retarget.c:341:12: error: 'g_ICE_Conneced' undeclared (first use in this function)
         if(g_ICE_Conneced)
            ^~~~~~~~~~~~~~
../Library/retarget.c:344:16: warning: implicit declaration of function 'SH_DoCommand' [-Wimplicit-function-declaration]
             if(SH_DoCommand(0x04, (int)g_buf, NULL) != 0)
                ^~~~~~~~~~~~
make: *** [Library/subdir.mk:116: Library/retarget.o] Error 1
```
3. Tried to naively fix the above errors by extracting the declaration of the global variables from the second `__GNUC__` directive. 
```
#if defined(DEBUG_ENABLE_SEMIHOST)
static char g_buf[16];
static char g_buf_len = 0;
static volatile int32_t g_ICE_Conneced = 1;
#ifndef __GNUC__
```
Which led to the next error:
```
arm-none-eabi-gcc -mcpu=cortex-m23 -march=armv8-m.base -mthumb -mlittle-endian -Og -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections  -g -T gcc_arm.ld -Xlinker --gc-sections -L"../CMSIS/GCC" -L"/home/user/Project/Debug/Library" -Wl,-Map,"NS-husky.map" --specs=rdimon.specs -o "NS-husky.elf"  ./User/main.o ./User/xom2_func.o ./User/xom3_func.o  ./Library/acmp.o ./Library/bpwm.o ./Library/can.o ./Library/crc.o ./Library/crypto.o ./Library/dac.o ./Library/eadc.o ./Library/ebi.o ./Library/ecap.o ./Library/epwm.o ./Library/fmc.o ./Library/gpio.o ./Library/i2c.o ./Library/i2s.o ./Library/pdma.o ./Library/qei.o ./Library/qspi.o ./Library/retarget.o ./Library/rtc.o ./Library/sc.o ./Library/scuart.o ./Library/sdh.o ./Library/spi.o ./Library/sys.o ./Library/timer.o ./Library/timer_pwm.o ./Library/uart.o ./Library/usbd.o ./Library/usci_i2c.o ./Library/usci_spi.o ./Library/usci_uart.o ./Library/wdt.o ./Library/wwdt.o  ./CMSIS/GCC/startup_M2351.o  ./CMSIS/system_M2351.o   -lnsc
./CMSIS/GCC/startup_M2351.o: In function `__PC':
/home/user/Project/Debug/../CMSIS/GCC/startup_M2351.S:462: undefined reference to `SH_Return'
collect2: error: ld returned 1 exit status
make: *** [makefile:47: NS-husky.elf] Error 1
```
4. At this point I realised that the `#ifdef` directives are totally messed up. I could not infer the correct order/logic. Tried to apply [the Keil semihosting fix](https://github.com/OpenNuvoton/M2351BSP/commit/a9918882bf799788250c8fb3916a90e114ac9583) without any luck. Importing the [current sample code for the semihosting under GCC](https://github.com/OpenNuvoton/M2351BSP/tree/master/SampleCode/Semihost) doesn't work either.

Note: It does not matter if `DEBUG_ENABLE_SEMIHOST=1` or `DEBUG_ENABLE_SEMIHOST=2` as some parts of the code require. Both configurations fail with the above messages.

## Suggested solution
Port the Keil MDK fix to GNU/Eclipse. Moreover, the default Nuvoton packets, which import sample source code when creating a new project in Eclipse, should also be updated when the fix is complete. The generated example source code **is expected** to contain enabled semihosting.  Reason is that the boilerplate contains statements such as
```
    printf("Secure is running ...\n");
```

```
    printf("\n");
    printf("+---------------------------------------------+\n");
    printf("|           Nonsecure is running ...          |\n");
    printf("+---------------------------------------------+\n");
```
which are **expected** to be seen by the user if they are generated.

**Comment by wschang0** [comment]
To enable semihost with GCC,
You should add “initialise_monitor_handles()” before calling printf in your code.

You also need add macro definition “OS_USE_SEMIHOSTING” in Properties->C/C++ General->Paths and Symbols->Symbols->GNU C

Set "Enable ARM semihosting" at Debug Configuration->Startup

You could take the semihost sample code as the example.

**Comment by 0xd35a2ee** [comment]
Applying these settings breaks the compilation. The reason is that `initialise_monitor_handles()` is not found by default. I needed to add `-specs=rdimon.specs -lc -lrdimon` to the linker (can be found in **Project -> Properties -> C/C++ Build -> Settings -> GCC Linker -> Linker flags**).

Nevertheless, the semihosting still does not work (no printf content is displayed on the openOCD terminal). Even after compiling/linking successfully and applying the rest of the steps.

**Comment by wschang0** [comment]
The semihosting of template project is test ok at our side.
Could you re-clone the latest BSP and re-install the NuEclipse tool, then follow the steps to try again?


1.      You should add “initialise_monitor_handles()” before calling printf in your code.

2.      You also need add macro definition “OS_USE_SEMIHOSTING” in Properties->C/C++ General->Paths and Symbols->Symbols->GNU C

3.      You could take the semihost sample code as the example.

4.      Click “Enable ARM semihosting” at Debug Configuration->GDB Nuvoton Nu-Link Debugging->Template Release->Startup->Enable ARM semihosting
