### ISSUE TITLE
Does Numaker PFM M2351 support TF-M now?

### ISSUE THREAD

**Issue by BabaYB** [OpenNuvoton/M2351BSP#3]
Hi, TF-M is an implementation of a part of PSA, can provide security based on trustzone-m. And I wanna try Numaker PFM M2351 with TF-M. So does Numaker PFM M2351 support TF-M now?
Thanks!

**Comment by wschang0** [comment]
There is no M2351 supporting on TF-M project yet.
Nuvoton plan to support it, but the schedule may be Q1 end of 2019.

**Comment by BabaYB** [comment]
OK, thanks.
