### ISSUE TITLE
Measuring Execution Time of a Piece of Code

### ISSUE THREAD

**Issue by user01-weeve** [OpenNuvoton/M2351BSP#5]
Hi,
I am trying to figure out exact number of CPU cycles taken by a piece of code. In one of the doc, I checked in use guide, DWT counter is mentioned in a block diagram which can be used to do this. But it doesn't work.
Below is the piece of code I tried:
uint32_t clock_cycles_counter;
volatile unsigned int *DWT_CYCCNT = (uint32_t *)0xE0001004; //address of the register
volatile unsigned int *DWT_CONTROL = (uint32_t *)0xE0001000; //address of the register
volatile unsigned int *SCB_DEMCR = (uint32_t *)0xE000EDFC; //address of the register
// configure and start the clock cycles counter
clock_cycles_counter = 0;
*SCB_DEMCR = *SCB_DEMCR | 0x01000000;
*DWT_CYCCNT = 0;
*DWT_CONTROL |=  1;
//////
//////Code to be measured
/////
// stop and get the counter value
*DWT_CONTROL &= ~1;
clock_cycles_counter = *DWT_CYCCNT;

// print the counter value
printf("counter %d\n\r", clock_cycles_counter);

Always get '0'. Is the peripheral address mapped in above program correct?
Has anyone tried another way to measure the time?
Thank in advance

**Comment by wschang0** [comment]
M2351 doesn’t support DWT cycle counter.
The clock source of SysTick could be the same as CPU.
Therefore, you could use SysTick timer for cycle count.
