### ISSUE TITLE
Flashing the Patched Executable Binary

### ISSUE THREAD

**Issue by user01-weeve** [OpenNuvoton/M2351BSP#6]
Hello,
I have generated a bare metal application binary(*.axf and *.bin) using Keil uVision IDE. Then I have modified the binary, the .bin file, (some part in application code segment, not the CRT or reset vectors).  I want to flash this patched .bin file on M2351 device. I found the .axf file is looked and flashed by IDE/tool but not *.bin file. As per my understanding *.axf is converted into flat binary and then flashed by flashing tool. Could you please let me know command/step/tool to flash the *.bin file directly?
Thanks

**Comment by wschang0** [comment]
NuMicro ICP Programming Tool should be what you are looking for.
You could download it from here:
https://m2351.nuvoton.com/resource/


Regards,
WS
