### ISSUE TITLE
 Numaker M2351 with mbedOS 

### ISSUE THREAD

**Issue by pramodjayram** [OpenNuvoton/M2351BSP#7]
Hi,
I am trying to run the example blynk code for NuMaker-PFM-M2351 using mbed-cli on ubuntu 18.04. I have generated the hex file using mbed -cli.
I have enabled MSG and upgraded the firmware of the board as well. But flashing the board with this hex code by drag and drop or with mbed CLI has no effect on the board. The blinking of led or serial print does not work after flashing of the code. I would appreciate if anyone could help me.

P.S I am using the below non secure sample code 
[https://github.com/OpenNuvoton/NuMaker-mbed-TZ-nonsecure-example](url)
Thank You

**Comment by cyliangtw** [comment]
Hi,
1. If the default partition is not changed, it's easy and you just flash the built-in secure image (`\mbed-os\targets\TARGET_NUVOTON\TARGET_M2351\TARGET_NUMAKER_PFM_M2351\TARGET_M23_NS`) in advance. Then, flash your non-secure blinky image.
2. If you want to change the partition, you must follow steps of readme in `NuMaker-mbed-TZ-nonsecure-example`, to build secure image and build non-secure image with new` cmse-lib.o` .

Which one do u prefer ?

**Comment by pramodjayram** [comment]
Hi,
Thank you for your response. I have tried both methods but none worked. After flashing the board with the non secure hex file, I dont see the led blinking neither do I see anything in the serial console.
I have enabled VCOM, TXD,RXD,MSG buttons.

**Comment by cyliangtw** [comment]
I just download standard [mbed-os-example-blinky](https://github.com/ARMmbed/mbed-os-example-blinky) and environment settings as:

- mbed-os version: mbed-os-5.12.0
- Mbed CLI build command: `mbed compile -m NUMAKER_PFM_M2351 -t ARMC6`
- Terminal program UART configuration: 9600/8-N-1

It's working well on my board.
Please verify your board by the attached hex files.

[m2351_hex.zip](https://github.com/OpenNuvoton/M2351BSP/files/3324354/m2351_hex.zip)

**Comment by pramodjayram** [comment]
I solved the issue. I had to drap and drop both the hex files at a time for it to work.

Thank You
